### ISSUE TITLE
API has been failing a lot recently, 504

### ISSUE THREAD

**Issue by rosspi** [BTCMarkets/API#10]
I've been getting a lot of 504 responses recently using the API:
http://pastebin.com/MeJtFWGQ

**Comment by JarrodCrane** [comment]
Hi rosspi,

I can confirm there were some issues with the API over the last 24 hours. The issue has been isolated to the order/history api call which has been temporarily disabled. All other API calls are available and should be performing normally. The order/history API call will be reinstated shortly.
