### ISSUE TITLE
Read-only API keys

### ISSUE THREAD

**Issue by soundasleep** [BTCMarkets/API#103]
Hello!

We would love to add support for BTCMarkets to [CryptFolio](https://cryptfolio.com), as [requested by one of your users](https://support.cryptfolio.com/i48-support-btcmarkets-api-manual-csv-import), but since the private API is read-write we're unable to support it.

Could you add functionality to generate a read-only API key? (Alternatively [add support for fine-grained permissions](https://github.com/BTCMarkets/API/issues/47).)

Thank you!

**Comment by justin-ngin** [comment]
Hi @soundasleep ,

This is an interesting idea, let me bring it up with the development team and see what can be done. I'll update this issue with info as I get it.

Thanks,
Justin

**Comment by Vertikar** [comment]
I'm the user mentioned above, would be handy to have this for other platforms like cryptofolio also.

**Comment by kylemantesso** [comment]
Further to this, could it be more granular and something that users could turn on/off for different features and trading amounts?

**Comment by Scotty79** [comment]
Requesting read only API level also for use in 3rd party crypto portfolio apps. Must have feature!

**Comment by shanebrunette** [comment]
I run https://myCryptoTaxCalculator.com and now that it is tax time I am getting a lot of users asking me about the read only API key issue. Users need it so they can pull in data to do their tax returns. I expect this request to increase over the next month...

**Comment by justin-ngin** [comment]
Hi @soundasleep, @Vertikar, @kylemantesso, @Scotty79, @shanebrunette 

While fine-grained permissions is still on the drawing board for later development, read-only API keys are here! Head over to the revamped [API Key page](https://www.btcmarkets.net/account/apikey) to start using them!

Cheers,
Justin
