### ISSUE TITLE
API for listing supported pairs

### ISSUE THREAD

**Issue by soundasleep** [BTCMarkets/API#104]
Have you considered an API which lists all available currencies/trading pairs?

**Comment by justin-ngin** [comment]
Hi @soundasleep ,

You would like an endpoint that simply responds with an array of all the possible trading pairs?

**Comment by soundasleep** [comment]
Yep! Right now I've hardcoded all of the currency pairs into this API worker of mine, but if/when you add new pairs I'd love to automatically start picking them up too.

**Comment by justin-ngin** [comment]
Got it. Any new currencies that would be listed on BTC Markets would be announced well in advance, but I will add this to the development backlog for the v2 API. Thanks for the suggestion.

Regards,
Justin

**Comment by soundasleep** [comment]
Thank you Justin! :)

**Comment by justin-ngin** [comment]
@soundasleep ,

As it turns out, this part of v2 has already been done and implemented in production. Send a GET request to endpoint /v2/market/active. Authentication is not required. Please let me know if you can successfully reach it.

Thanks,
Justin

**Comment by soundasleep** [comment]
That works great! Thank you!
