### ISSUE TITLE
Incorrect daily change calculation

### ISSUE THREAD

**Issue by squeaky-nose** [BTCMarkets/API#106]
Hi,
I've noticed that the way your calculating daily change percentage is (in my opinion) incorrect.

EG. assume...
day open is $100
current price is $120
the daily change would be $20

btcmarkets.net calculates the percentage as 20/120*100 = 16.16%
however it should be 20/100*100 = 20%

Is this a known issue or an 'industry standard'?

**Comment by martin-nginio** [comment]
Hi @sushant40 

Thank you for your feedback.

We have released a new version of trading API with improved ticker information.
https://api.btcmarkets.net/doc/v3#section/Introduction
 
The new Ticker API data for daily price change, low and high price as per below example:
https://api.btcmarkets.net/v3/markets/BTC-AUD/ticker

Please also note that `day` refers to the past 24 hours. If you come across issues pls let us know. 

Thanks. 

Regards,
Martin
