### ISSUE TITLE
API requests

### ISSUE THREAD

**Issue by MarginWarriors** [BTCMarkets/API#108]
Hi!

I am representing Chinese fund of traders Margin Warriors. Please tell me conditions how we can receive access to 3000 API requests per 10 minutes?

Thanks

**Comment by justin-ngin** [comment]
Hi @MarginWarriors ,

We are always looking to increase trading capacity through the API. For the moment, we cannot give access above the advertised limits. We will update the wiki if/when those limits change. If you have very specific needs in regard to volume, please contact the [support desk](https://btcmarkets.net/support)

Regards,
Justin
