### ISSUE TITLE
Sample responses for /order/detail

### ISSUE THREAD

**Issue by CatherineGracey** [BTCMarkets/API#115]
Hi.

Is it possible to add some sample responses to the Trading-API page for the `/order/detail` path? I would like to know what to expect if my order is fully matched, partially matched, and not at all matched, and what an unsuccessful response looks like. Does the response change based on a market or limit order?

Thanks.

**Comment by justin-ngin** [comment]
Hi @CatherineGracey ,

I recently updated the [wiki page for trading](https://github.com/BTCMarkets/API/wiki/Trading-API). There should be an example for each of the specific instances you mentioned. The response format does not change based on order side. Should you include an invalid order number in the request array, no data will be returned for that specific order. Similarly, if you only have one invalid order number in the array, the orders array in the response will be empty.

Please let me know if you have any more questions.

Cheers,
Justin

**Comment by CatherineGracey** [comment]
That's exactly what I needed, thanks. I don't suppose you have listed anywhere the minimum order sizes for your trading pairs?

**Comment by martin-nginio** [comment]
Hi @CatherineGracey 

Thanks for your feedback. 

Our existing APIs did not expose `minimum order size` but we are just releasing a new API version that would have this feature you are referring to.

Documentation:
https://api.btcmarkets.net/doc/v3#section/Introduction

API call with list of markets and minimum order sizes:
https://api.btcmarkets.net/v3/markets

Thanks. 

Regards,
Martin

**Comment by martin-nginio** [comment]
closing the issue.
