### ISSUE TITLE
Suggestion for extra ruby code sample 

### ISSUE THREAD

**Issue by matthewbretherton** [BTCMarkets/API#118]
You may wish to add this example kine of code to your '**Sample Code**' section

 puts b.post_order_open( {"currency":"AUD","instrument":"BTC","limit":10,"since":0})

on the https://github.com/nolim1t/btcmarkets-gem page 

It offers an example of a **post** with **parameters** and may save people reading the code closely to understand the mapping within method missing to a well formed request 

Rgds 
matthew@bretherton.id.au

**Comment by justin-ngin** [comment]
Hi @matthewbretherton ,

This Ruby client is not officially supported sample code, and as we don't own it, we have no influence over their documentation. If you would like to see their documentation updated, I suggest you create this issue on their GitHub page directly.

Cheers,
Justin
