### ISSUE TITLE
API BTCMarkets Input to Excel

### ISSUE THREAD

**Issue by zacharybrnabic** [BTCMarkets/API#119]
All,

I have a MacBook Pro and I am wanting to input data from this website / API https://api.btcmarkets.net/market/XRP/AUD/orderbook into excel. However, I want it to update automatically, every 1 second, 1 minute or whatever I set it to myself, how can I achieve this?

ZAC

**Comment by justin-ngin** [comment]
Hi @zacharybrnabic ,

A brief google search suggests that an implementation of this on a Mac version of excel could be quite complicated, as it seems the simplest excel add-in candidate is not compatible with Mac. At this time, we don't have any official or suggested implementations of this. If we develop one or I come across anything that may be helpful, I'll update this issue and/or our documentation.

Regards,
Justin

**Comment by wilsoff** [comment]
You could do it with python and write to a csv (or xlsx) if you import the appropriate libraries. But it’ll take some coding.
