### ISSUE TITLE
Order history is not working

### ISSUE THREAD

**Issue by quentinadam** [BTCMarkets/API#12]
I get the following error when I try to request the /order/history endpoint :

{"success":false,"errorCode":5,"errorMessage":"order history is currently unavailable"}

This has been the case for nearly two weeks now. Any idea when this will be back working ?

**Comment by JarrodCrane** [comment]
Hi Quentin,

We expect this to be back available next week.

**Comment by JarrodCrane** [comment]
Hi Quentin,

This is now available again.
