### ISSUE TITLE
Automatic trades

### ISSUE THREAD

**Issue by aaron1971** [BTCMarkets/API#122]
Hi, is it possible to set up automatic trades on a BTC Markets platform. If so, how?

**Comment by justin-ngin** [comment]
Hi @aaron1971 ,

Could you please give a more specific description about what you would like to do? You can place limit orders through the website or the API, and if you wish to have a completely automated system making trades based off of some criteria that you set, you can do that with a program utilizing the API. 

Regards,
Justin
