### ISSUE TITLE
API antiddos protection

### ISSUE THREAD

**Issue by alexsith** [BTCMarkets/API#125]
Hello. I requested to support to add my IP to whitelist because your API server return antiddos page even at first request. I don't know why they told me create ticket here.
I used different UserAgent - one from your example. other from my browser. It didn't help.

Trace: 

Request: GET https://api.btcmarkets.net/account/balance {'accept': 'application/json', 'Content-Type': 'application/json', 'apikey': '4e*******a', 'timestamp': '1519759119151', 'signature': 'ZEG********dg==', 'User-Agent': 'btc markets python client', 'Accept-Encoding': 'gzip, deflate'} None 
NetworkError exception: ('btcmarkets https://api.btcmarkets.net/account/balance GET 403 <!DOCTYPE html>\n\n\n\n <html class="no-js" lang="en-US"> \n<head>\n<title>Attention Required! | Cloudflare</title>\n<meta name="captcha-bypass" id="captcha-bypass" />\n<meta charset="UTF-8" />\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />\n<meta name="robots" content="noindex, nofollow" />\n<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />\n<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />\n\n<style type="text/css">body{margin:0;padding:0}</style>\n\n<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>\n<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>\n\n\n</head>\n<body>\n <div id="cf-wrapper">\n <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>\n <div id="cf-error-details" class="cf-error-details-wrapper">\n <div class="cf-wrapper cf-header cf-error-overview">\n <h1 data-translate="challenge_headline">One more step</h1>\n <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> api.btcmarkets.net</h2>\n </div>\n \n <div class="cf-section cf-highlight cf-captcha-container">\n <div class="cf-wrapper">\n <div class="cf-columns two">\n <div class="cf-column">\n \n <div class="cf-highlight-inverse cf-form-stacked">\n <form class="challenge-form" id="challenge-form" action="/cdn-cgi/l/chk_captcha" method="get">\n <script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal" data-ray="3f3d7dc4dba54f14" async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>\n <div class="g-recaptcha"></div>\n <noscript id="cf-captcha-bookmark" class="cf-captcha-info">\n <div><div style="width: 302px">\n <div>\n <iframe src="https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0&quot; frameborder="0" scrolling="no" style="width: 302px; height:422px; border-style: none;"></iframe>\n </div>\n <div style="width: 300px; border-style: none; bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25px; background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">\n <textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;"></textarea>\n <input type="submit" value="Submit"></input>\n </div>\n </div></div>\n </noscript>\n</form>\n\n </div>\n </div>\n\n <div class="cf-column">\n <div class="cf-screenshot-container">\n \n <span class="cf-no-screenshot"></span>\n \n </div>\n </div>\n </div>\n </div>\n </div>\n\n <div class="cf-section cf-wrapper">\n <div class="cf-columns two">\n <div class="cf-column">\n <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>\n \n <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>\n </div>\n\n <div class="cf-column">\n <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>\n \n\n <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>\n\n <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>\n \n </div>\n </div>\n </div>\n \n\n <div class="cf-error-footer cf-wrapper">\n <p>\n <span class="cf-footer-item">Cloudflare Ray ID: <strong>3f3d7dc4dba54f14</strong></span>\n <span class="cf-footer-separator">&bull;</span>\n <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 89.31.107.14</span>\n <span class="cf-footer-separator">&bull;</span>\n <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer&quot; id="brand_link" target="_blank">Cloudflare</a></span>\n \n </p>\n</div>\n\n\n </div>\n </div>\n\n <script type="text/javascript">\n window._cf_translation = {};\n \n \n</script>\n\n</body>\n</html>\n',)

**Comment by martin-nginio** [comment]
Hi @alexsith 

Thanks for your feedback. 

We recently had another customer reporting similar issues and now have a process to investigate those cases where CloudFlare block the request and help solving them. 

If this is still happening please let us know and we can investigate it further. We may need some more data from you (e.g. ip address) that you can share by opening a ticket with our support team. 

By the way, we have developed new generation of API that comes with several improvements and new features. Please feel free to check it below and If you have any questions please let us know. 
https://api.btcmarkets.net/doc/v3#section/Introduction

Thanks again. 

Regards,
Martin
