### ISSUE TITLE
Potential API bug

### ISSUE THREAD

**Issue by scoshil** [BTCMarkets/API#129]
Hi,

At 22:30:55 on 19/03/18 (Sydney time, UTC+11) my script suddenly alerted me to an issue. Upon looking into it, it appears at that time (give or take 1 second) my script suddenly thought the XRP/AUD book looked exactly the same as the BTC/AUD book.

It appears that BTC/AUD, ETH/AUD and LTC/AUD were unaffected at that time.

The next run of the same call 1 second later (for XRP/AUD orderbook) returned the correct order book again.

Unfortunately I cannot 100% rule out a bug in my own code, however I have been running the same script with no functional changes for several days without issue, and have been running the same code again since this incident without it occurring again, so it does not appear to be an issue with my code (barring any very rare race conditions).

Could you see if you can find any potential issues on your side, or any irregularities detected at that time?

Thanks

**Comment by justin-ngin** [comment]
Hi @scoshil ,

Could you elaborate on what you mean by "thought the XRP/AUD book looked exactly the same as the BTC/AUD book"? Were you getting orderbook through the websocket or through the API? Would you happen to have any logs of this instance?

Thanks,
Justin

**Comment by scoshil** [comment]
@justin-ngin 

I was getting the info from REST API, using the /orderbook endpoint. I requested the XRP/AUD orderbook at that time, and the info returned was that of the BTC/AUD book. The next call (1 second later) it was back to the correct/expected XRP/AUD data.

Unfortunately I don't have logs (that provide more info than I have already mentioned at least)

**Comment by martin-nginio** [comment]
Hi @scoshil 

Thanks for your feedback.

Our team is releasing a new version of WebSocket feed which improves many aspect of the existing solution so please feel free to take a look at the documentation here and let us know if you have any questions.: 

https://github.com/BTCMarkets/API/wiki/WebSocket-v2-%28beta%29

Thanks.

I'm closing this issue as we are unable to re-produce it.
