### ISSUE TITLE
Error with open orders API

### ISSUE THREAD

**Issue by quentinadam** [BTCMarkets/API#13]
When requesting the /order/open endpoint, I get the following open orders :

{ success: true,
  errorCode: null,
  errorMessage: null,
  orders: 
   [ { id: 113210644,
       currency: 'AUD',
       instrument: 'BTC',
       orderSide: 'Ask',
       ordertype: 'Limit',
       creationTime: 1467603319137,
       status: 'Placed',
       errorMessage: null,
       price: 90924000000,
       volume: 69283199,
       openVolume: 69283199,
       clientRequestId: null,
       trades: [] },
     { id: 113210676,
       currency: 'AUD',
       instrument: 'BTC',
       orderSide: 'Ask',
       ordertype: 'Limit',
       creationTime: 1467603320074,
       status: 'Placed',
       errorMessage: null,
       price: 91209000000,
       volume: 473186621,
       openVolume: 473186621,
       clientRequestId: null,
       trades: [] },
     { id: 113210545,
       currency: 'AUD',
       instrument: 'BTC',
       orderSide: 'Ask',
       ordertype: 'Limit',
       creationTime: 1467603306793,
       status: 'Placed',
       errorMessage: null,
       price: 92566000000,
       volume: 349349684,
       openVolume: 349349684,
       clientRequestId: null,
       trades: [] } ] }

However, there do not seem to be any open orders when I look at my open orders through the website.
Also, when I try to cancel them I get the following error :

{ success: true,
  errorCode: null,
  errorMessage: null,
  responses: 
   [ { success: false,
       errorCode: 3,
       errorMessage: 'order is already cancelled.',
       id: 113210676 } ] }

Can you please check why the open orders API is returning orders which seem to be closed ?

**Comment by JarrodCrane** [comment]
This issue has now been fixed.
