### ISSUE TITLE
Invalid Argument / Two Factor Authorisation

### ISSUE THREAD

**Issue by AusCustomSoft** [BTCMarkets/API#133]
How are the trading API's accessed when the account has a two factor authorisation.
I am following the API javascript examples and constantly receiving the error "Invalid Argument" when an "automated" trade is attempted to be placed.
If a currency that is not supported by this account is selected - the correct response of "Account holder does not support currency" is displayed.

I can only surmise that I am missing something related to TFA.
The nodeJS example doesn't include any support for Two Factor Authorisation.

// ----- output below -------------//
// First three are valid arguments in all cases
// second three are for currency that is not in the account....
//---------------------------------//
arbServer listening on port 5000!
BTC Markets - Add Order
Promise rejected.
failed POST request to url https://api.btcmarkets.net/order/create with message /order/create
1524803867730
{"currency":"AUS","instrument":"BTC","price":1000000,"volume":100000000,"orderSide":"Bid","ordertype":"Limit","clientRequestId":null}. Success: false. Error message: Invalid argument.
BTC Markets - Add Order
Promise rejected.
failed POST request to url https://api.btcmarkets.net/order/create with message /order/create
1524803873033
{"currency":"AUS","instrument":"ETH","price":1000000,"volume":100000000,"orderSide":"Bid","ordertype":"Limit","clientRequestId":null}. Success: false. Error message: Invalid argument.
BTC Markets - Add Order
Promise rejected.
failed POST request to url https://api.btcmarkets.net/order/create with message /order/create
1524803876464
{"currency":"AUS","instrument":"LTC","price":1000000,"volume":100000000,"orderSide":"Bid","ordertype":"Limit","clientRequestId":null}. Success: false. Error message: Invalid argument.
BTC Markets - Add Order
Promise rejected.
failed POST request to url https://api.btcmarkets.net/order/create with message /order/create
1524803887094
{"currency":"USD","instrument":"BTC","price":1000000,"volume":100000000,"orderSide":"Bid","ordertype":"Limit","clientRequestId":null}. Success: false. Error message: Account holder does not support currency
BTC Markets - Add Order
Promise rejected.
failed POST request to url https://api.btcmarkets.net/order/create with message /order/create
1524803889929
{"currency":"USD","instrument":"ETH","price":1000000,"volume":100000000,"orderSide":"Bid","ordertype":"Limit","clientRequestId":null}. Success: false. Error message: Account holder does not support currency
BTC Markets - Add Order
Promise rejected.
failed POST request to url https://api.btcmarkets.net/order/create with message /order/create
1524803892686
{"currency":"USD","instrument":"LTC","price":1000000,"volume":100000000,"orderSide":"Bid","ordertype":"Limit","clientRequestId":null}. Success: false. Error message: Account holder does not support currency

**Comment by justin-ngin** [comment]
Hi @AusCustomSoft ,

When trying to place an order with Australian dollars as the currency, the correct abbreviation is `AUD`. BTCMarkets does not support trading in USD at this time. This isn't shouldn't be related to 2FA. Please let me know if that resolves your issues.

Regards,
Justin

**Comment by AusCustomSoft** [comment]
Fantastic - - it works - Many thanks...
