### ISSUE TITLE
Can this api be used to get a coin price at a certain date/timestamp?

### ISSUE THREAD

**Issue by JackSilburn** [BTCMarkets/API#136]
I'm new to using APIs in programming. 

I am wondering if I can input a date (or timestamp) and the API will return the price of a chosen coin (e.g. BTC, ETH) at that particular time?

Thank you and apologies if this is the wrong place to post this.

**Comment by aljp** [comment]
There's no way to do this with BTCMarkets API as far as I'm aware.

**Comment by welldrake** [comment]
See potential solution here: https://github.com/BTCMarkets/API/issues/79#issuecomment-400892668

**Comment by justin-ngin** [comment]
Hi @JackSilburn, @aljp 

We've just released a new endpoint for retrieving our entire history of tick/candle data in minute, hour, or day resolution. Check out the docs [here!](https://github.com/BTCMarkets/API/wiki/Market-data-API#historical-ticks)

Cheers,
Justin
