### ISSUE TITLE
Success response for Fund-Transfer does not include fundsTransferId

### ISSUE THREAD

**Issue by robbiem** [BTCMarkets/API#137]
Hi I'd like to request that you include `fundsTransferId` in the success response when creating a new Funds Transfer.

I'd like to save this value when creating the transfer and then use it as a reference when iterating over the results returned from `/fundtransfer/history`

`fundsTransferId` is included for each transfer when querying `/fundtransfer/history` but doesn't seem to be used anywhere else in the system.

**Comment by justin-ngin** [comment]
Hi @robbiem ,

I'm adding this request to the development backlog for consideration by the dev team. Thanks for using BTCMarkets.

Cheers,
Justin
