### ISSUE TITLE
error with order history?

### ISSUE THREAD

**Issue by rosspi** [BTCMarkets/API#14]
I've noticed the API recently (must've been within past two months) seems to no longer give me correct results for my order history:
I send this:
"{\"currency\":\"AUD\",\"instrument\":\"BTC\",\"limit\":15,\"since\":0}"
And my response is:
"{\"success\":true,\"errorCode\":null,\"errorMessage\":null,\"orders\":[]}"
Which is not correct. I have some orders!

**Comment by rosspi** [comment]
It would be nice if there could be a response on this.
Basically I think the api is broken!!

**Comment by JarrodCrane** [comment]
Hi Ross, 

There are currently no known issues specifically with the order history API call. Can you please email support@btcmarkets.net so we can look into your issue further?

**Comment by rosspi** [comment]
Hi @JarrodCrane , I have emailed support last Thursday, but not response yet.

**Comment by JarrodCrane** [comment]
Hi Ross, apologies for the lack of communication. I can see your request has been escalated by support and you will receive a response in a day or two.
