### ISSUE TITLE
Fund transfer email authorisation

### ISSUE THREAD

**Issue by barry254** [BTCMarkets/API#141]
Hi, I'm writing an application that uses the fund transfer function of the API and was just wondering how to get around the issue of needing to verify fund transfers by clicking an email link. I noticed that the sample response didn't have a status of pending authorization so I am guessing that this is possible. Please let me know how to proceed. Cheers.

**Comment by shazbert** [comment]
@barry254 I think I might come across this issue as well, I think a faster approach would be to use the API of the email service you are using and send a general get request with the link provided just as an initial work around, big headache but only if you don't get a response.

**Comment by justin-ngin** [comment]
Hi @barry254 ,

Currently, there isn't a way around it. I know it kind of defeats the purpose of using the API for this. It's definitely on our list of things to address, and I hope to have an answer and a solution for you soon.

Cheers,
Justin

**Comment by martin-nginio** [comment]
Hi @barry254 

I can confirm that we have removed the need to verify withdrawls  that are created via API. 

If you are still getting issues pls let us know.  

Thanks.

Regards,
Martin
