### ISSUE TITLE
Cant retrieve opposite coin pairs via API

### ISSUE THREAD

**Issue by spraddles** [BTCMarkets/API#143]
Using the API via HTTP, I can get info on a coin pair like ETH/BTC:
https://api.btcmarkets.net/market/ETH/BTC/tick

...but I can't get info on the opposite coin pair (BTC/ETH).

e.g. this does not work:
https://api.btcmarkets.net/market/BTC/ETH/tick

Is there another method I should be using to get this info, or is that API only designed to give specific coin pairs, and not other?

Thanks.

**Comment by justin-ngin** [comment]
Hi @badsprad,

We do not have a BTC/ETH market. Currently, we only offer trading pairs with AUD and BTC as currencies i.e. you can buy or sell instruments for AUD or BTC, but for example you cannot "sell" BTC for ETH. Please let me know if you have any other questions.

Cheers,
Justin
