### ISSUE TITLE
is there any way to get anything other than the most recent 200 items for orders history

### ISSUE THREAD

**Issue by npomfret** [BTCMarkets/API#145]
The since parameter seems pointless.  The response the items are ordered most recent, and the first one is my most recent item regardless of what value i used for 'since'.

Can I get my entire history starting at order zero?

**Comment by justin-ngin** [comment]
Hi @npomfret ,

Have you had a chance to try out the new [v2 order history endpoint](https://github.com/BTCMarkets/API/wiki/Trading-API#order-history-1) yet? Please try it out and let me know how it works for you!

Regards,
Justin

**Comment by npomfret** [comment]
@justin-ngin finally getting round to doing this.  I think this [docs](https://github.com/BTCMarkets/API/wiki/Authentication) are wrong for the v2 get operations:

> 2- URI Note the request parameters
> /v2/order/trade/history/ETH/AUD?indexForward=true&limit=10&since=698825
> 3- current timestamp in milliseconds
> 1519429556662
> The string to sign is:
> '/account/balance' + '\n' + indexForward=true&limit=10&since=698825 + '\n' + '1519429556662' + '\n'
> 

The string to sign in this example should be what exactly?

**Comment by martin-nginio** [comment]
Hi @npomfret 

The string to sign in this case would be:
``` 
/v2/order/trade/history/ETH/AUD  + '\n' + indexForward=true&limit=10&since=698825 + '\n'  + 1519429556662
```

In general for GET APIs, the string to sign is:
```
path + '\n' + queryString + '\n' + timestamp 
```

Please let me know if this works for you,. Also if there is specific part of the doc is wrong (I assume you are referring to the entire authentication section) please let us know and we will fix it. 

Thanks for your feedback. 

Regards,
Martin

**Comment by npomfret** [comment]
Thanks yes, I figured it out.  My point was more that the documentation is wrong/misleading.

**Comment by npomfret** [comment]
@martin-nginio is the new `fundtransfer/history` api call a v2 endpoint?

**Comment by martin-nginio** [comment]
thanks @npomfret for letting us know.  The doc will be reviewed and fixed and I can see the example for GET authentication does not have the correct path in it.
