### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by npomfret** [BTCMarkets/API#146]
can you please add the ability to get all open orders (across all markets) in a single request?

**Comment by justin-ngin** [comment]
Hi @npomfret ,

We have this on the development backlog, and hope to start working on it soon. Thanks for being a part of the BTC Markets community!

Cheers,
Justin

**Comment by justin-ngin** [comment]
Hi @npomfret 

This endpoint has arrived! Check out the docs [here](https://github.com/BTCMarkets/API/wiki/Trading-API#open-orders-1).

Cheers,
Justin

**Comment by sossee2** [comment]
Hi Justin

I can't find it in the docs. Is it /order/open?

**Comment by justin-ngin** [comment]
My apologies,

I didn't realize the doc updates to that page weren't saved. Try the link again
