### ISSUE TITLE
[websockets] What does the "trades" field mean in the `MarketTrade` event

### ISSUE THREAD

**Issue by mitchmindtree** [BTCMarkets/API#147]
I'm testing the `MarketTrade` event but don't quite understand the data returned under the "trades" field. An example of a returned event:
```js
{
    "id": 0,
    "timestamp": 0,
    "marketId": 2001,
    "agency": "BTCMarkets",
    "instrument": "BTC",
    "currency": "AUD",
    "trades": [
        [1532333307052, 1040000000000, 1589225, 2038602603]
    ]
}
```
Could you please explain:

1. what the 4 elements in the inner "trades" array mean and
2. what does it mean to get more than one element in the outer "trades" array?

Thanks for your time!

**Comment by JoshuaBatty** [comment]
Also requiring further detail about what the trades array represents. Haven't been able to find anything so far.... Can anyone provide a quick description of what the 4 fields in the array represent? Thanks.

**Comment by ahmohamed** [comment]
Unofficial answer here. The four elements in "trades" correspond to [timestamp (in milliseconds), price (multiplied by 1e8), amount (multiplied by 1e8), trade_id]

**Comment by mitchmindtree** [comment]
Perfect, thanks so much!

**Comment by justin-ngin** [comment]
The answer provided by ahmohamed is correct. In addition, if there is more than one element in the trades array, each element represents one trade since the last socket event. We're looking to give some love to the websocket and its documentation soon.

Cheers,
Justin

**Comment by JoshuaBatty** [comment]
Thanks @justin-ngin +1 for more web socket support. Especially those account related events that keep getting teased ;)

**Comment by JoshuaBatty** [comment]
This issue can probably be closed now.
