### ISSUE TITLE
Calling historic data endpoint with "paging.newer" request immediately returns single record

### ISSUE THREAD

**Issue by squeaky-nose** [BTCMarkets/API#154]
Hi,
I would have thaught that 'immediately' calling the 'paging.newer" endpoint returned by the historic data endpoint would return no data - however it returns a single item.

Is this so that we can 'overwrite' the data on our end for that particular timestamp since it may have changed?

**Comment by justin-ngin** [comment]
Hi @sushant40 ,

It is only returning a datapoint because the `since` parameter is inclusive. It is not meant to indicate that calling the `newer` endpoint would necessarily give you an updated candle. In fact, we don't recommend polling this endpoint for real-time candle updates. 

Cheers,
Justin
