### ISSUE TITLE
Open orders API seems to be lagging

### ISSUE THREAD

**Issue by codeandvisual** [BTCMarkets/API#163]
Hi there, if I create some orders via the API and then call the /order/open end point immediately afterwards it doesn't always return the order just created. 

Subsequent queries do show the orders present though, so it seems like a lag issue.

**Comment by sossee2** [comment]
I noticed the same issue over a year ago

**Comment by martin-nginio** [comment]
Hi @codeandvisual 

Thank you for your feedback. 

Given the nature of the trading platform and API, most operations are asynchronous so there is always a delay between time of placing the order and the time it executes and the order detail is updated.  

I can also confirm that getting order details via calling `/order/open` API may have some delays and I'm hoping our engineering team can improve this in the coming months.  

Depending on your specific needs and if 200-400 milliseconds makes a difference in your application then  I'd suggest using `/order/detail` as it has update time (hence you will get the latest order detail quicker) and it may be helpful in some situations. Please also note that this API requires you to pass the order Id that you'd have received when calling `/order/create` API.   

Hope this helps.

Thanks. 

Regards,
Martin

**Comment by martin-nginio** [comment]
Hi @codeandvisual  and @sossee2 

For the past few months our dev team has made several improvements in latency of APIs and particularly open order API. 

If you are still experiencing issues please let us know. 

By the way, we have developed new generation of API `v3` that is a full set with several improvements and new features. Please feel free to check it below:
https://api.btcmarkets.net/doc/v3#section/Introduction

`API v3` is still in beta and will be released in the coming weeks. If you have any questions please let us know. 

Thanks again. 

Regards,
Martin

**Comment by martin-nginio** [comment]
closing the issue given the recent improvements and updates.
