### ISSUE TITLE
WebSocket v2 - tradeId always 0

### ISSUE THREAD

**Issue by gabrieldodan** [BTCMarkets/API#166]
Hi,

I subscribe to ``trade`` channel and the trade messages always has tradeId=0

Any idea? 

Thanks!

**Comment by martin-nginio** [comment]
Hi @gabrieldodan 

Thank you for your feedback. 

I can confirm this is a bug that was introduced earlier this week as a result of a platform upgrade. 
tradeIds should not be zero for WebSocket messages. 

I'm sorry for the inconvenience and our dev team will fix this by end of the week. 

Thanks.    

Regards,
Martin

**Comment by martin-nginio** [comment]
Closing the ticket as the issue was fixed at the time.

Thanks @gabrieldodan  for your feedback.
