### ISSUE TITLE
WebSocket v2 - trade type

### ISSUE THREAD

**Issue by gabrieldodan** [BTCMarkets/API#167]
Would be great if you could add trade type:buy/sell on ``trade`` event

Thanks!
Gabriel

**Comment by martin-nginio** [comment]
Hi @gabrieldodan 

Thank you for your feedback. 

This is to confirm that `side` has been added to WebSocket feed `trade` event:
https://api.btcmarkets.net/doc/v3#section/Trade-event 

Regards,
Martin

**Comment by martin-nginio** [comment]
closing the issue. Thanks @gabrieldodan
