### ISSUE TITLE
some wrong with API

### ISSUE THREAD

**Issue by RudenkoPJ** [BTCMarkets/API#17]
When i take https://api.btcmarkets.net/market/ETH/BTC/orderbook from my browser (Chrome) i get 
JSON responce `{"currency":"BTC","instrument":"ETH","timestamp":1498230551,"asks":[[0.12356417,12.0],[0.12356418,0.00998372],[0.12356419,36.0],[0.12358,8.16],[0.124,2.88],[0.124531,0.34109796],[0.12580217,29.0],[0.135,0.05],[0.13899998,1.0],[0.139988,1.0],[0.144,1.98],[0.14458551,3.8373632],[0.146,0.99023059],[0.14875,0.29],[0.14999999,1.9],[0.15,2.25],[0.15200037,2.0],[0.161,0.29],[0.1999998,19.853103],[0.2,1.9510109],[0.2,2.0],[0.220664,30.89484],[0.25,0.78259708],[0.5,2.0],[0.55,20.0],[1.0,1.0]],"bids":[[0.11811116,4.275633],[0.11811115,4.275633],[0.11811115,37.0],[0.1181,0.00168004],[0.118,3.2132212],[0.117,0.05],[0.116,0.05],[0.115,0.05],[0.11463925,0.62445752],[0.114,0.05],[0.113,0.05],[0.1121,10.0],[0.112,0.05],[0.112,0.02],[0.1115,4.9179198],[0.111,0.05],[0.11,0.05],[0.11,1.0],[0.1091,14.596598],[0.109,0.2],[0.109,5.0],[0.105,1.0],[0.104,0.2],[0.1024,2.0],[0.1,7.0],[0.1,0.1],[0.1,0.1],[0.1,18.848196],[0.099,0.1],[0.09847644,1.647569],[0.098,0.05],[0.098,0.1],[0.098,15.0],[0.097,0.1],[0.096,0.1],[0.095,0.1],[0.095,1.0],[0.094,0.1],[0.093,0.1],[0.092,0.1],[0.091,0.1],[0.09,11.345877],[0.09,12.0],[0.089,0.1],[0.088,0.1],[0.087,0.1],[0.086,0.1],[0.086,4.0],[0.06122454,11.002101],[0.06,1.663008],[0.051,4.0],[0.05,5.0],[0.01,0.5],[4.3302E-4,0.5],[1.0E-8,7777.0]]}`
When i try use custom library https://github.com/RyanCarrier/btcmarketsgo and use method GetOrderBook i get page with `            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>`
I thought that the author has some mistake 
And write code , and take the same error with CAPTCHA
That is not normal

**Comment by RyanCarrier** [comment]
Hey Mate, I tried running GetOrderBook with ETH/BTC and it seemed to work fine...

![image](https://user-images.githubusercontent.com/9389452/27613783-e1f0effe-5be0-11e7-82c0-6237ffffc04e.png)

Do you have your keys set up correctly?

**Comment by RudenkoPJ** [comment]
Hmmm order book its a public method if it wants keys its something wrong
with API, because I can get access from my browser , but when I trying from
go client her API send me page with captcha, if u need some screenshots , I
can send it tomorrow

**Comment by JarrodCrane** [comment]
Hi, this could be due to some ip restriction we have in place for certain areas. Can you please email support@btcmarrkets.net with the ip address that you are calling the API from?

**Comment by RyanCarrier** [comment]
![image](https://user-images.githubusercontent.com/9389452/27819914-b2acea50-60df-11e7-8810-1b34a1fe36a8.png)
I just tested without keys, I'll need to make some changes to get that working. Though it "shouldn't" be used without keys there is no reason for the public methods to not work without keys.

I'll get onto that soon

Ryan Carrier
