### ISSUE TITLE
Please include the fees and limits in the /v3/markets endpoint

### ISSUE THREAD

**Issue by fatduckling** [BTCMarkets/API#171]
Hi,
I was just wondering whether it's possible to include the following details in the /v3/markets endpoint for each supported trading pair:

- Default trading fee (the trading fee no trading activity has occurred in the month, eg 0.85%)
- Minimum deposit amount
- Maximum deposit amount
- Minimum withdraw amount
- Maximum withdraw amount
- Deposit fee
- Withdraw fee

Thank you!

**Comment by martin-nginio** [comment]
Hi @fatduckling 

Thank you for your feedback. 

You should be able to get min/max amounts for deposit/withdraw via `/v3/assets` API as per below:
https://api.btcmarkets.net/doc/v3#tag/Fund-Management-APIs/paths/~1v3~1assets/get

The same API also returns fee for deposit and withdrawals as well as number of decimal points allowed.   

As for trading fees, at this stage we have different rules for crypto pairs vs AUD pairs and soon will also include maker/taker so the default can be dependent on multiple variables. At this stage, we recommend using the existing API `/v3/accounts/me/trading-fees`  and our team will consider publishing default fees in later iterations of the API.  

Thanks  again for your support. 

Regards,
Martin

**Comment by fatduckling** [comment]
Oh I didn't even see this endpoint. Thank you so much!!
