### ISSUE TITLE
API v3 sort order

### ISSUE THREAD

**Issue by DavidTangye** [BTCMarkets/API#175]
In https://api.btcmarkets.net/doc/v3#section/General-notes :
> 
> Sort order
> By default, all lists are sorted ascending, meaning the most recent items appear first in the list.

That will be descending, if sorted on a timestamp.

**Comment by martin-nginio** [comment]
Thanks @DavidTangye  for your feedback. 

You are right and this is a mistake in our documentation. 

Records always return newer to older hence descending sort order is correct always (unless specified otherwise). 

We will get the documentation fixed shortly. 

Thanks.

Regards,
Martin

**Comment by martin-nginio** [comment]
Closing the ticket as the documentation has been updated.
