### ISSUE TITLE
BTC Markets Trading data API

### ISSUE THREAD

**Issue by AussieBloomin** [BTCMarkets/API#179]
I need help to create a GET address to receive all the bid and ask information from BTC Markets.

https://api.btcmarkets.net/v3/markets/?marketId=ETH-BTC&marketId=XRP-BTC/ticker

gives me all the assets but no bid and ask info. output is 

[{"marketId":"BTC-AUD","baseAssetName":"BTC","quoteAssetName":"AUD","minOrderAmount":"0.0001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"LTC-AUD","baseAssetName":"LTC","quoteAssetName":"AUD","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"LTC-BTC","baseAssetName":"LTC","quoteAssetName":"BTC","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"ETH-BTC","baseAssetName":"ETH","quoteAssetName":"BTC","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"ETH-AUD","baseAssetName":"ETH","quoteAssetName":"AUD","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"ETC-AUD","baseAssetName":"ETC","quoteAssetName":"AUD","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"ETC-BTC","baseAssetName":"ETC","quoteAssetName":"BTC","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"XRP-AUD","baseAssetName":"XRP","quoteAssetName":"AUD","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"4"},{"marketId":"XRP-BTC","baseAssetName":"XRP","quoteAssetName":"BTC","minOrderAmount":"0.01","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"POWR-AUD","baseAssetName":"POWR","quoteAssetName":"AUD","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"4"},{"marketId":"POWR-BTC","baseAssetName":"POWR","quoteAssetName":"BTC","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"OMG-AUD","baseAssetName":"OMG","quoteAssetName":"AUD","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"4"},{"marketId":"OMG-BTC","baseAssetName":"OMG","quoteAssetName":"BTC","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"BCHABC-AUD","baseAssetName":"BCHABC","quoteAssetName":"AUD","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"BCHABC-BTC","baseAssetName":"BCHABC","quoteAssetName":"BTC","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"BCHSV-AUD","baseAssetName":"BCHSV","quoteAssetName":"AUD","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"BCHSV-BTC","baseAssetName":"BCHSV","quoteAssetName":"BTC","minOrderAmount":"0.001","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"GNT-AUD","baseAssetName":"GNT","quoteAssetName":"AUD","minOrderAmount":"0.15","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"4"},{"marketId":"GNT-BTC","baseAssetName":"GNT","quoteAssetName":"BTC","minOrderAmount":"0.15","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"BAT-AUD","baseAssetName":"BAT","quoteAssetName":"AUD","minOrderAmount":"0.06","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"4"},{"marketId":"BAT-BTC","baseAssetName":"BAT","quoteAssetName":"BTC","minOrderAmount":"0.06","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"},{"marketId":"XLM-AUD","baseAssetName":"XLM","quoteAssetName":"AUD","minOrderAmount":"0.1","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"4"},{"marketId":"XLM-BTC","baseAssetName":"XLM","quoteAssetName":"BTC","minOrderAmount":"0.1","maxOrderAmount":"1000000","amountDecimals":"8","priceDecimals":"2"}]

thank you for your assistance

**Comment by martin-nginio** [comment]
Hi @AussieBloomin 

You should be able to use the following API in order to retrieve ticker information for a given market.  
`/v3/markets/{marketId}/ticker`

Also, if you want to get ticker inforamtion for multiple markets then the below API can be useful:
`/v3/markets/tickers`  (you can pass multiple marketIds as query params)

More inforamtion about those APIs can be found here: 
https://api.btcmarkets.net/doc/v3/#tag/Market-data-APIs/paths/~1v3~1markets~1tickers/get

Thanks.

Regards,
Martin

**Comment by AussieBloomin** [comment]
I already use
https://api.btcmarkets.net/market/BAT/AUD/tick

but I want multiple markets and the following API doesn't work
https://api.btcmarkets.net/v3/markets/?marketId=ETH-BTC&marketId=XRP-BTC/ticker
<https://api.btcmarkets.net/v3/markets/?marketId=%22ETH-BTC%22&marketId=%22XRP-BTC%22/ticker>


nor does
/v3/markets/tickers

**Comment by martin-nginio** [comment]
The correct path would be:
https://api.btcmarkets.net/v3/markets/tickers?marketId=ETH-BTC&marketId=XRP-BTC

**Comment by AussieBloomin** [comment]
Thank you very much.

That works perfectly.

**Comment by martin-nginio** [comment]
closing the issue. Thanks @AussieBloomin
