### ISSUE TITLE
Parse JSON returns 

### ISSUE THREAD

**Issue by KieranMills** [BTCMarkets/API#180]
path: /market/BTC/AUD/tick
returns
{"bestBid":844.0,"bestAsk":844.98,"lastPrice":845.0,"currency":"AUD","instrument":"BTC","timestamp":1476242958,"volume24h":172.60804}

Maybe good idea in future to parse the JSON with PYTHON? if this exists already? 
Thanks

**Comment by KieranMills** [comment]
I think I've just figured out it returns as a dict so there is no problem.

**Comment by martin-nginio** [comment]
Hi @KieranMills 

Thanks for your feedback and I'm glad you figured it out. 

Please also note that we have a new version of the trading API (v3) as per below:
https://api.btcmarkets.net/doc/v3/#tag/Market-data-APIs/paths/~1v3~1markets~1{marketId}~1ticker/get

Regards,
Martin

**Comment by KieranMills** [comment]
Thanks very much martin! Im sure i will run into some more problems soon
:).
