### ISSUE TITLE
Generation of deposit addresses via API

### ISSUE THREAD

**Issue by ArtyomVir** [BTCMarkets/API#185]
Hi! can I generate new addresses for depositing crypro to my account through the API?
For instance, I want to generate a new address for each of my users and each of them will have their 'own' address to deposit crypto

**Comment by martin-nginio** [comment]
Hi @ArtyomVir 

Thanks for your feedback.

You should be able to use the following API to get deposit address:
https://api.btcmarkets.net/doc/v3/#tag/Fund-Management-APIs/paths/~1v3~1addresses/get

Regards,
Martin

**Comment by martin-nginio** [comment]
Thanks @ArtyomVir.  closing the ticket.
