### ISSUE TITLE
Authentication Error on 'order/create' and 'tradingfees' endpoints only

### ISSUE THREAD

**Issue by benjii** [BTCMarkets/API#22]
Hi,

I have been successfully using the BTC Markets API for a while, but when I attempt to use either of the above endpoints I always get an authentication failure. I am signing the requests consistently and always using this code;

> ssl_sign = OpenSSL::HMAC.digest('sha512', Base64.decode64(key), message)
> Base64.encode64(ssl_sign).to_s.gsub("\n",'')

For the trading fee endpoint, for example, I set:

URI: /account/ETH/AUD/tradingfee
timestamp: [current time]
signature: [the base64 encoded signature]

And I always get:

> @body="{\"success\":false,\"errorCode\":1,\"errorMessage\":\"Authentication failed.\"}"

So I am a bit lost on why I am hitting this error on these endpoints only. Do I need special API access to use these methods perhaps?

Thanks for your help!
Ben

**Comment by martin-nginio** [comment]
Hi,

calling tradingfee endpoint requires the same permission that you use for any other private API calls so no need for special permissions here. The only difference is you use Http Get instead of post for this endpoint and there is no post data. 

So the String that you sign should look like the following:
```
/account/ETH/AUD/tradingfee
1502343935094

```

Also, just checking that you are passing `timestamp, apikey and signature` with the http header. 

Also, assuming you already have checked timestamp at your end.

Please can you confirm if all above is ok.

**Comment by benjii** [comment]
Thank you for getting back to me. I can now call the `tradingfee` endpoint (bug in the code at my end). However, I am stilling having trouble with `order/create`.

Here is what I am passing to this endpoint (I am trying to trade $1AUD for whatever ETH I can get at the current price):

uri: `/order/create`
payload: `{"currency":"AUD","instrument":"ETH","price":39500000000,"volume":253164.55696202532,"orderSide":"Bid","ordertype":"Limit","clientRequestId":"1"}`
timestamp: `1502691734872`

Which yields the following HMAC:

`wUIMLi5zpoNcMEDN6WfEUC+x/lXJwMBzmJggt8n9WYQs2WgmqMOjHQzbJkqXuydodnz8++AYsS/gsAyJMVpG/w==`

I am not too sure about the `volume` and `price` fields. I have multiple by 100000000 (satoshi's in a bitcoin) because it was in the examples... but this is ETH, so I am not sure.

In any case, whatever I try I always get:

`{"success"=>false, "errorCode"=>1, "errorMessage"=>"Authentication failed."}`

I have double (and triple) checked the order of my HTTP headers, so I am at a bit of a loss...

Thanks again!
Ben

**Comment by martin-nginio** [comment]
ETH is similar to BTC from API input/output perspective. 

Both `price` and `volume` variables (same as all other monetary related fields) are in satoshi (e.g. ETH volume of 1 is sent and received as 100000000) 

So  in your case volume would be: 
`"volume":25316455696202` (please note that only 8 decimal points are allowed)

If you can please update those fields and if you still get Auth error please let me know.

**Comment by benjii** [comment]
Ok, that worked! Thank you.

In case this is helpful to anyone else, when I had a value that was too _low_ (or perhaps with a decimal point, I'm not sure exactly what triggered the problem) I got an authentication error. This seems to stand in for "bad request".

If I had a value that was too _high_ I get what you'd expect - an "insufficient funds" error.

Thanks again @martin-nginio ! :)

**Comment by martin-nginio** [comment]
thanks @benjii. You are right and the error message does not represent the actual issue.  Our team will certainty add this to the backlog either for API new version v2 or improvement to the existing API.  I'm closing the issue.
