### ISSUE TITLE
Fund Transfer: withdrawCrypto, no withdraw tag?

### ISSUE THREAD

**Issue by manuwaik** [BTCMarkets/API#24]
I am looking to withdraw Ripple.
Is there any API request to be able to send to a specific address and tag?

Only address accessible with current request:
`{"amount":10000000,"address":"1EJKj147QmEzywLnLpuxSr6SoPr1p62VBX","currency":"XRP"}
`

**Comment by martin-nginio** [comment]
When calling withdrawCrypto API for XRP, if you need to pass destination tag then please use the following format:

`{"amount":10000000,"address":"1EJKj147QmEzywLnLpuxSr6SoPr1p62VBX?dt=123456","currency":"XRP"}`

in this case value of `dt` can be any integer. 

If you come across any issues please let us know. 

Thanks.
