### ISSUE TITLE
/order/history endpoint not returning all orders.

### ISSUE THREAD

**Issue by rosspi** [BTCMarkets/API#26]
The call to /order/history is not bringing back my most recent order (it's an AUD - Ethereum order if that makes a difference).
I can see on your website it is listed there in my account, but it is not there in the API response.

Your api seems to have something wrong with it every week! You guys need separate environments to work safely within rather than post to twitter about the live env being in an unreliable state all the time. I'm making assumptions here, but that's what it seems like is going on.

**Comment by martin-nginio** [comment]
Hi @rosspi 

I'm sorry to see you are experiencing issues with our API. 

Regarding API endpoint not returning your orders, generally our metrics do not show any issues at this stage so if you can see a specific order on our website and not in API this is something our tech team needs to investigate as the underlying data is the same and there should not be inconsistencies.

As this github page is a public, please can you send your username or account information to our support desk and if you can please share information about particular order you have issues with and our team can investigate further. 

We also had to have our system down for a scheduled maintenance earlier this week but I understand we should continue to improve communication and also advance notice in such situations. 

Thank you.

**Comment by rosspi** [comment]
Hi martin.
I have used the contact support tool, but yet to receive a response, automated or not.
I have supplied the evidence of lacking records in the response.
Looking forward to the response.
I hope there's some silly mistake on my part, cause otherwise it's pretty poor.
