### ISSUE TITLE
Account balance Api Question

### ISSUE THREAD

**Issue by erangadbw** [BTCMarkets/API#27]
Hello BTCmarket Development team.

I have noticed that you have recently changed the account balance JSON response to now include a new section 'pendingFunds'.

Is this pendingFunds information only supposed to show funds incoming when we are depositing money/ funds leaving when we are withdrawing  money, or will it change when we are selling and buying crypto within the exchange?

Also how do we discern weather this pendingfunds value is incoming funds or leaving funds.

Thanks

**Comment by martin-nginio** [comment]
Hi @erangadbw 

You will have funds in pending funds in the following situations:

1. When you have open orders (buy or sell order). more detail can be found here: https://btcmarkets.net/faq#q20

2. When you request to withdraw funds(e.g. withdraw $100 AUD) and this is only between time that you request and time that withdraw is processed(which is usually a short timeframe). 

There will be no pending funds if you make a deposit.

Hope this helps.   

Thanks. 

Regards,
Martin
