### ISSUE TITLE
Buy/Sell Side in Trade History

### ISSUE THREAD

**Issue by Sqlaroche** [BTCMarkets/API#28]
Is there a way to extract which side a trade transaction occurred on? Currently only the amount, trade ID, price, and date are shown. Is there a planned upgrade to provide this information?

**Comment by martin-nginio** [comment]
Hi @Sqlaroche 

if you are referring to `/order/trade/history` API then there is already a parameter called `side` that is part of the response body which specifies the side of the trade that was executed under your account.

For public API (e.g. `market/BTC/AUD/trades` ) there is always two sides for any trade.

If you are looking for anything other than above please let us know. 

Thanks.  

Regards,
Martin

**Comment by Sqlaroche** [comment]
Sorry for the ambiguity... I was referring to the public API. Yes, I understand that a trade necessarily involves two sides, but usually exchange APIs will list whether trades were taker buys or taker sells in their trade history. Am I correct in assuming there is no way to do this with the information provided?

**Comment by martin-nginio** [comment]
I can confirm that at this stage our public API does not support taker or maker side for trade executions.  

Thanks.
