### ISSUE TITLE
POST requests not authenticating in PHP

### ISSUE THREAD

**Issue by budlee85** [BTCMarkets/API#29]
Hi there,

Having trouble figuring out why my POST request is returning an Authentication failed error.  I took the code from the previous post and changed method to POST and added content which was the request data (in json)

    public function history($count = 10, $since = 0 )
    {
		
		$method = '/order/history';
        $data = [
            'currency' => 'AUD',
            'instrument' => 'BTC',
            'limit' => $count,
            'since' => $since ,
        ];
		
		$secret_key_encoded = base64_decode($this->secret);

		$nonce = round(microtime(true) * 1000); 

        // build query string

		$msg = $method. "\n" . $nonce . "\n";
		if(count($data)) {
			$data = json_encode($data). "\n";
			$msg .= $data;
		}
		
		echo "Message is:\n" . $msg;

		$encodedMsg =   hash_hmac('sha512', $msg, $secret_key_encoded, true);
		$base64Msg = base64_encode($encodedMsg); 
		
		echo "Encoded Message is: \n" . $base64Msg . "<br>\n";
		
		// Create a stream
		$opts = array(
		  'http'=>array(
				'method'=>"POST",
				'header'=>      "Accept: */*\r\n" .
								"Accept-Charset: UTF-8\r\n" .
								"Content-Type: application/json\r\n" .
								"apikey: " . $this->key . "\r\n" .
								"timestamp: " . $nonce . "\r\n" .
								"User-Agent: btc markets php client\r\n" .
								"signature: " . $base64Msg . "\r\n",
				'content'=> $data
		  )
		);

		$context = stream_context_create($opts);

		var_dump($opts);
                echo "\n\n";
		// Open the file using the HTTP headers set above
		$response = file_get_contents('https://api.btcmarkets.net'.$method, false, $context);

		print_r($response);
        if ($response === false)  {
            return false;
        }
        
        $result = json_decode($response, true);
        if (!$result) {
            return false;   
        }                
        
        return $result;
    }

**Comment by budlee85** [comment]
Figured it out, if you are giving POST parameters, the request data doesn't need to end in \n like a GET query

**Comment by martin-nginio** [comment]
Hi @budlee85 

thanks for the note.  I can see in other programming languages we add "\n" for post data when using POST method. Please feel free to add your working code here or let us know and we can list your sample PHP code on the main API page. 

Thanks.  

Regards,
Martin

**Comment by budlee85** [comment]
All good,

Rather than
$data = json_encode($data). "\n";
I removed the last \n at the end of the string to be

$data = json_encode($data);
