### ISSUE TITLE
24h volume in ticker API?

### ISSUE THREAD

**Issue by DanielFragaBR** [BTCMarkets/API#3]
Hi! Would it be possible to add the latest 24h volume in the ticker API?
https://api.btcmarkets.net/market/BTC/AUD/tick
I want to add BTCMarkets to my site:
http://exchangewar.info
and it would be nice if the ticker returned the 24h volume too.
Thank you.

**Comment by JarrodCrane** [comment]
Hi Daniel,

This is something we are looking at adding soon. A few sites have requested this.

Cheers,

Jarrod.
