### ISSUE TITLE
ripple destination tag

### ISSUE THREAD

**Issue by jumpinjoey222** [BTCMarkets/API#31]
does the API support destination tags for ripple withdraw?

**Comment by martin-nginio** [comment]
Hi @jumpinjoey222 

Yes it does.

When calling withdrawCrypto API for XRP, pass destination tag as part of the address as per following sample:

`{"amount":10000000,"address":"1EJKj147QmEzywLnLpuxSr6SoPr1p62VBX?dt=123456","currency":"XRP"}`

in this case value of `dt` can be any integer.

Thanks.

**Comment by jumpinjoey222** [comment]
thanks martin appreciate the help and the quick response
