### ISSUE TITLE
Authentication fails for /order/create, but not other resources

### ISSUE THREAD

**Issue by robmcd** [BTCMarkets/API#33]
Hi, I'm trying to use the API via python for the first time. I'm using the resources from here: https://github.com/BTCMarkets/api-client-python

I am able to successfully perform API calls that require authentication (like checking my account balance, account trading fee, open orders). However, I get the authentication failure when i try to create an order.

When I try to create a very small order as a test, the order creation gets a failure response. Is there a minimum order size?

order create data: {"currency":"AUD","instrument":"ETH","price":37563920000.0,"volume":5255.491404396225,"orderSide":"Bid","ordertype":"Limit","clientRequestId":"removed"}

response data: 
{u'errorCode': 1, u'errorMessage': u'Authentication failed.', u'success': False}

**Comment by martin-nginio** [comment]
Hi @robmcd 

The input numbers (volume and price in order create API) should not have decimal points in them.  

Also, the sample python code has been updated with some improvements and the sample create order call should work here:
https://github.com/BTCMarkets/api-client-python/blob/master/main.py

Thanks. 

Regards,
Martin

**Comment by robmcd** [comment]
Thanks. Removing the decimal points fixed the Authentication issue. I later encountered an "Invalid Amount" issue which was resolved by rounding the bid price to 2 decimal places (represented as integer with the  x 100000000 multiplier)

**Comment by davewd** [comment]
Would be awesome to specify the int in the API documentation @martin-nginio

**Comment by martin-nginio** [comment]
thank you for the suggestion. I added a note for decimal points.
