### ISSUE TITLE
Retrieve current trading fee via the API

### ISSUE THREAD

**Issue by rdmarsh** [BTCMarkets/API#4]
Is it possible to retrieve the current trading fee via the API?

**Comment by meganaught** [comment]
I'd like to know this too.

**Comment by jeneaux** [comment]
This would be a huge help, I'd like to see this implemented

**Comment by JarrodCrane** [comment]
Hi guys, thanks for your feedback. This is now available and is documented on https://github.com/BTCMarkets/API/wiki/Account-API
