### ISSUE TITLE
"limit" parameter ignored in /order/open request

### ISSUE THREAD

**Issue by nikolaisid** [BTCMarkets/API#42]
/order/open: {"currency":"AUD","instrument":"XRP","limit":1,"since":0}
returns ALL the open orders for AUD/XRP rather than just 1.

/order/history: {"currency":"AUD","instrument":"XRP","limit":1,"since":0}
returns 1 order, as specified.

/order/open: {"currency":"AUD","instrument":"LTC","limit":1,"since":0}
returns ALL the open orders for AUD/LTC rather than just 1.

Apologies if I'm missing something obvious.

**Comment by martin-nginio** [comment]
Hi @nikolaisid 

You are correct and the `limit` condition when calling `order/open` API does not have any impact. This decision was made at the time to ensure that API users always get all open orders in a single call given they may need to process open orders in a short timeframe avoiding pagination. 

Having said that the current API needs "limit" to be passed hence you can pass any integer or null value to get it working. 

Our team is aware and will consider this as an improvement to the new version of API. 

Thanks for your feedback and sorry for the confusion. 

Regards,
Martin

**Comment by nikolaisid** [comment]
Ah, thanks for clearing that up!
