### ISSUE TITLE
No info on Market order type?

### ISSUE THREAD

**Issue by mattwithoos** [BTCMarkets/API#48]
On the Trading API there are no examples of the Market order type, nor whether the price is required.

If you're creating a Market order and have $100 AUD to spend, why do you need to enter volume?

If you're creating a Market order and have 1 Bitcoin to sell, why do you need to enter the price?

Surely these are optional? If not, I'd appreciate seeing a sample JSON request for a Market order.

edit: Please and thank you :)

**Comment by martin-nginio** [comment]
hi @mattwithoos 

Thanks for your feedback.

The current API requires all parameters to be available regardless of order types. In case of placing Market orders, the price will be ignored, however you will need to specify one.  

Below is a sample json input for placing a market order.

{"currency":"AUD","instrument":"LTC","price":6700000000,"volume":100000000,"orderSide":"Bid","ordertype":"Market","clientRequestId":"1"}

The current API also does not support situation when you only want to specify dollar amount to spend hence you'll always need to specify order volume.   

I hope this helps. 

Regards,
Martin

**Comment by mattwithoos** [comment]
Awesome, thank you Martin! 👍  :)
