### ISSUE TITLE
API call for trading fee

### ISSUE THREAD

**Issue by danKHUU** [BTCMarkets/API#49]
Hi,

Is there a API call to retrieve trading fee? 

Thanks

**Comment by martin-nginio** [comment]
Hi @danKHUU 

You can find information about trading Fee API here: 
https://github.com/BTCMarkets/API/wiki/Account-API#get-trading-fee

Thanks. 

Regards,
Martin

**Comment by danKHUU** [comment]
Hi @martin-nginio thank you.

Do you have a sample?

Regards,
Dan

**Comment by martin-nginio** [comment]
The following is an example in Python calling for calling account balance API. Trading fee API is similar as it uses Http GET and similar authentication. The only difference is you will have currency pairs in the URL: `/account/BTC/AUD/tradingFee`

https://github.com/BTCMarkets/api-client-python/blob/master/btcmarkets.py

Below also covers API client in other languages:
https://github.com/BTCMarkets/API#sample-codes-created-by-third-parties

If you come across issues please feel free to post it here. 

Regards,
Martin

**Comment by danKHUU** [comment]
Thank you Martin.

**Comment by marksy-91** [comment]
Just a note for others that visit this page, the correct URL is '/account/{instrument}/{currency}/tradingfee'. Notice the API documentation uses '/tradingfee' and not '/tradingFee'.

If /tradingFee is used, a HTTP Error will be returned.
