### ISSUE TITLE
withdraw api

### ISSUE THREAD

**Issue by rosspi** [BTCMarkets/API#5]
Is there, or when will there, be an API for withdrawing and depositing to our accoutns?

**Comment by stefanqin** [comment]
I would like to know this as well.

**Comment by joevon** [comment]
Hi,

Are there currently any plans to withdraw funds to your bank account? Would be much appreciated.

Joey

**Comment by martin-nginio** [comment]
Hi,

There is an existing API for requesting to withdraw AUD or Crypto via API.  Here is more info:

http POST 
`/fundtransfer/withdrawEFT`

sample Input: 
`{"accountName":"John Smith","accountNumber":"12345678","bankName":"ANZ","bsbNumber":"123456","amount":500000000,"currency":"AUD"}`
  
sample output
`{success":true,"errorCode":null,"errorMessage":null,"status":"Pending Authorization"}`

 Authentication for this API and parameter passing is similar to all other http ports and account related APIs. 

Hope this helps. I will update the documentation as well.

**Comment by martin-nginio** [comment]
closing the issue. thanks.
