### ISSUE TITLE
no trade side on MarketTrade websocket event

### ISSUE THREAD

**Issue by gabrieldodan** [BTCMarkets/API#53]
Hi , there is no information regarding trade side(buy or sell) on MarketTrade event. Are there any workaround ? I see that on the website on "Last 50 Trades" box the trades have different colors .

**Comment by DaveJMir** [comment]
Looks like the red/green in "Last 50 Trades" is just whether the price moved up/or down.

The javascript that populates that box simply does `if(price<prevPrice){}` to add the price-up/down css style

**Comment by martin-nginio** [comment]
Hi @gabrieldodan and @cheriff 

Thanks for your feedback. 

Trade side has been part of our API v3 as per below: 
https://api.btcmarkets.net/doc/v3/#section/Trade-event

I'm closing the issue. 

Thanks.

Regards,
Martin
