### ISSUE TITLE
Market API doesn't support USD for BTC?

### ISSUE THREAD

**Issue by consultantcraig** [BTCMarkets/API#58]
When you visit this link:

https://api.btcmarkets.net/market/BTC/AUD/orderbook

You'll get the order book data in AUD.

When you visit this link:

https://api.btcmarkets.net/market/BTC/USD/orderbook

An error (error code 5) is returned.

Is USD not supported in this context?  I was unable to find a list of accepted currency codes.  Thanks!

**Comment by martin-nginio** [comment]
Hi @consultantcraig 

USD trading is not supported at this stage. If we decide to support USD, it will be announced to our customers. 

Thanks.  

Regards,
Martin

**Comment by consultantcraig** [comment]
Thanks Martin.   Turns out many exchanges do not support USD (I'm working on an exchange aggregation console) and I'll have to do real-time currency conversion in several cases, going to try money.js.
