### ISSUE TITLE
Order details issue

### ISSUE THREAD

**Issue by RyanCarrier** [BTCMarkets/API#59]
You can see by this below, the post request is receiving a 200 response and success:true but no actual details about the order. The second debug line is the raw response from the server. The info below is just once parsed.

I sent an email and they forwarded me here. All other requests work as with creating orders; so my signing is fine as far as I can tell.

![image](https://user-images.githubusercontent.com/9389452/32359788-196a8290-c09c-11e7-8887-8280c503fce0.png)

**Comment by RyanCarrier** [comment]
Using this; https://github.com/RyanCarrier/btcmarketsgo

Here is the request itself;
https://github.com/RyanCarrier/btcmarketsgo/blob/master/order.go#L309-L320

Here is the signing and posting, the same snippet as used when creating orders and doing all other signed requests;
https://github.com/RyanCarrier/btcmarketsgo/blob/master/util.go#L58-L93

And here is the signing if needed;
https://github.com/RyanCarrier/btcmarketsgo/blob/master/util.go#L30-L33

**Comment by martin-nginio** [comment]
Hi @RyanCarrier 

I can confirm that your application correctly calls the order detail API and is working fine.

please note that  order detail API only returns the order information if you are the account owner of the order.  Please ensure to use API keys that belong to the user who created the order in the first place. 

Thanks.  

Regards,
Martin

**Comment by wsdefghjk-23124** [comment]
I have started receiving this same response on Bid orders fully matched recently, at the moment I can query very old orders with correct response, and some of the more recent ones only return success with no further information.

I can confirm this is not related to change on API keys nor incorrect Auth.

**Comment by justin-ngin** [comment]
Hi @wsdefghjk-23124 , 

Could you please provide some of the order numbers that are yielding the empty response?

Thanks,
Justin

**Comment by wsdefghjk-23124** [comment]
Hi @justin-ngin 
These are some of the Orders that return only a "success" and no further info....
 1302897232
 1302485555
 1302782819
 1287601752

Thanks
W

**Comment by justin-ngin** [comment]
Hi @wsdefghjk-23124 ,

These would appear to be trade IDs and not order IDs. If you check your trade history and find the trades with these IDs, the orderID info will be returned. You can then plug these orderIDs into your array to get the details.

```java
{ success: true,
  errorCode: null,
  errorMessage: null,
  trades: 
   [ { id: 1202613712,
       creationTime: 1517456016310,
       description: null,
       price: 1637200,
       volume: 27538946,
       side: 'Ask',
       fee: 60585,
       orderId: 1201986823 } ] }
```

Hope this helps. We will look into adding a tradeDetails endpoint similar to order details so that you can look up trades specifically by id.

Cheers,
Justin
