### ISSUE TITLE
Serious issue: Unable to cancel order with the API

### ISSUE THREAD

**Issue by quentinadam** [BTCMarkets/API#6]
Some of the cancel order requests that I issue seem to get stuck somewhere, and I get the following error :

errorCode: 3, 
errorMessage: 'order cancellation is in progress.'

Once this issue appears it is impossible to cancel the order, even by issuing later cancel requests. The order stays open forever without possibility to cancel it via the API.

I have contacted support but they do not seem to be able to solve the issue.

**Comment by moneroexamples** [comment]
It seems to be working now, at least from my current tests.

**Comment by JarrodCrane** [comment]
Hi,

Yes I can confirm this issued has now been addressed.
