### ISSUE TITLE
How to know transaction processing state?

### ISSUE THREAD

**Issue by ravivlb** [BTCMarkets/API#60]
I am using API and generating the QR code with my wallet address. So user can pay using their own wallet by reading QR or typing address and amount. After this, how can I get the status of the transaction like pending or done/waiting.

**Comment by martin-nginio** [comment]
Hi @ravivlb 

You can use fund transfer history API in order to get list of transfers. Each fund transfer comes with status as per below.
https://github.com/BTCMarkets/API/wiki/Fund-Transfer-API#fund-transfer-status

Please let me know if this meets your requirement.  

Thanks. 

Regards,
Martin

**Comment by martin-nginio** [comment]
Hi @ravivlb 

Please feel free to refer to our latest API document:
https://api.btcmarkets.net/doc/v3/#section/Introduction 

I'm closing the issue.

Thanks.

Regards,
Martin
