### ISSUE TITLE
Securing my API

### ISSUE THREAD

**Issue by Maxwilliam1690** [BTCMarkets/API#61]
Hi,

How are you able to keep my API key safe and secure on the platform?

Is there a way in which I can take it off the platform, to prevent it from being hacked?

Also, I have referred many people to your website to deposit cash and invest in cryptocurrencies - are there any rewards you offer for doing so?

Cheers,
Max

**Comment by martin-nginio** [comment]
HI @Maxwilliam1690 

Our team continuously improves the security of our platform and protecting our customer data. 

I'd encourage you to contact our support team to discuss referral scheme.

Thanks for your feedback.    

Closing the issue. 

Regards,
Martin
