### ISSUE TITLE
Getting date from path: /market/BTC/AUD/trades

### ISSUE THREAD

**Issue by juuunior** [BTCMarkets/API#66]
Hi,

In response I have date like this: "date":1378878093
How can convert it to "dd-mm-YYYY HH:mm" format?
Would be grete to explanation of this concept in WiKi.

Thanks.

**Comment by ShervinDD** [comment]
Depends on what language you are using. Just google the programming language and "convert unix timestamp"

**Comment by juuunior** [comment]
Thanks
