### ISSUE TITLE
Historial data

### ISSUE THREAD

**Issue by motoadz** [BTCMarkets/API#67]
Hi,
I'm struggling to find a way to pull historical candlestick data from btcmarkets?
Is there a way todo this?
Thanks

**Comment by meeeee12** [comment]
I am doing something like this by grabbing the data from the last 500 trades using: /market/BTC/AUD/trades . I then use the google charting library to create the candlesticks. 

Note: If you want more than the last 500 trades then you are going to also need your own server that will regularly grab the latest changes from btcmarkets and store it in your own database.

**Comment by welldrake** [comment]
See potential solution here: https://github.com/BTCMarkets/API/issues/79#issuecomment-400892668

**Comment by justin-ngin** [comment]
Hi @motoadz 

We've just released a new endpoint for retrieving our entire history of tick/candle data in minute, hour, or day resolution. Check out the docs [here](https://github.com/BTCMarkets/API/wiki/Market-data-API#historical-ticks)!

Cheers,
Justin
