### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by EkaterinaNesterenko** [BTCMarkets/API#69]
Hi,
we receive 403 error. 
This happens because when the server refers to this address https://api.btcmarkets.net/market/BTC/AUD/tick we can see that there is a captcha on the page. The server can’t put a tick that’s why it receive 403 error and return to us 500 error.
Could you please advise something?
Thanks.

**Comment by martin-nginio** [comment]
Hi @EkaterinaNesterenko 

Normally there is no captcha or restriction for API calls. Please can you contact our support desk, mention your username and also your external ip so they can investigate in case if there are any restrictions.

Thanks. 
 
Regards,
Martin
