### ISSUE TITLE
Market Data Tick - Add 24 hour change %

### ISSUE THREAD

**Issue by jacobjozwiak** [BTCMarkets/API#71]
Can you please add the 24 hour change % to the tick data, or is there some other way to get this data?

**Comment by alistaircross** [comment]
Did we get anywhere on this? I am looking for market data for the change in day, either in a percentage or in a dollar value?

Is there a way to calculate it?

**Comment by stephenyao** [comment]
Also wanting this, did anyone find a way to get this?

**Comment by stephenyao** [comment]
Alas, there doesn't seem to be a way to do this. Inspecting the js source from btcmarkets.net, they seem to have a function which loops through all the trades from the previous day and find the trade that happened 24 hours ago, and compares it with the last sale price to get the price change...

**Comment by justin-ngin** [comment]
Hi all,

I am adding this to our development backlog. If the engineering team can't get to it for a v1 implementation, it will certainly be considered for the v2. Thanks for your input!

Regards,
Justin
