### ISSUE TITLE
Unable to connect to WebSocket

### ISSUE THREAD

**Issue by mick-h** [BTCMarkets/API#73]
I've been attempting to connect to the websocket stream for the last day or two, and keep getting a 522 on ws and 504 on wss.  Is there a problem with the websocket feed?  I have not even gotten as far as using code, am using a websocket client extension in chrome.  https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo
I can connect to other websockets fine using this client (GDAX, Poloniex)

**Comment by limx0** [comment]
+1

**Comment by micahbule** [comment]
I'm able to connect with the websocket server, but I'm not receiving any events from their end. Falling back to long-polling for now.

**Comment by frankzhao** [comment]
@micahbule I wrote an example python client, maybe it helps - see my comment on https://github.com/BTCMarkets/API/issues/38#issuecomment-356239257

**Comment by micahbule** [comment]
@frankzhao apparently the HTTPS one works and yours didn't. I just tried it again. Dunno why it stalled yesterday though.

**Comment by martin-nginio** [comment]
Hi @mick-h 

Thanks for your feedback.

Our team is releasing a new version of WebSocket feed which improves many aspect of the existing solution so please feel free to take a look at the documentation here and let us know if you have any questions.:

https://github.com/BTCMarkets/API/wiki/WebSocket-v2-%28beta%29

Thanks.

I'm closing this ticket.
