### ISSUE TITLE
API account info auth failed

### ISSUE THREAD

**Issue by ghost** [BTCMarkets/API#77]
I'm trying to do a simple GET request using the below powerShell code

`$publicKey = "937887ad-e81b-49d8-8cba-4bff65f4d91a"
$privateKey = "e59SLPZmM0gPBMmEXINkevVJgUh9mMIrRmasDYOI/zl1+0FmJ2j7EiUeQY9cabAbQLhVJWC+/3rbdQ06rtqvEA==" #made up key
$baseURL = "https://api.btcmarkets.net/account/balance" #/order/history"
$path = "/account/balance"
$date1 = Get-Date -Date "01/01/1970"
$date2 = Get-Date
$millis = [math]::Round((New-TimeSpan -Start $date1 -End $date2).TotalMilliseconds) - 39600000

$stringToSign = $path + "`r`n" + $millis

$hmacsha = New-Object System.Security.Cryptography.HMACSHA512
$hmacsha.key = [Text.Encoding]::ASCII.GetBytes($privateKey)
$signature = $hmacsha.ComputeHash([Text.Encoding]::ASCII.GetBytes($stringToSign))
$signature = [Convert]::ToBase64String($signature)
$signature

$headers = @{ #ConvertTo-JSON 
    'Accept' = 'application/json';
    'Accept-Charset' = 'UTF-8';
    'Content-Type' = 'application/json';
    'apikey' =  $publicKey;
    'timestamp' = $millis;
    'signature' = $signature
}

Invoke-RestMethod -ContentType application/json -Method GET -Uri $baseURL -headers $headers`

I keep running into an authentication error - I know its not an issue with the timestamp because i get a timestamp error if i mess around with it. 
if i set $millis = 1234567890123, using the $privateKey i get the following result from SHA512:

PiU0MH//CeqlVIbEKHx/pH6uZhYHGseEt5F+7Id8EFg878OudSSX4bqG75l969X202heevKznGa58XnziRiYXA==

any help would be appreciated... thanks in advance!

**Comment by ghost** [comment]
i have also tried using "*/* as the value for the accept header (as i have seen in other examples
as well as having a new line character at the end of $stringToSign (as well as all combinations of these)

**Comment by meeeee12** [comment]
I am also having problems, but I think you are supposed to decode your private key from base64 before use.

**Comment by meeeee12** [comment]
I got mine working, and yes you need to decode your private key (secret key) before using it.

**Comment by shihanpietersz** [comment]
@meeeee12 ,
 how did you get it working. Can you share your code please. Been struggling with this for days now. Same error message Authentication error

Thanks again

**Comment by meeeee12** [comment]
@shihanpietersz 
I am not using powershell.

**Comment by ghost** [comment]
yeah, i gave up on powershell and used java instead. works fine now

**Comment by shihanpietersz** [comment]
Thanks guys. 
I think their is a fundamental issue on on the server end. even the sample C# code does not work. I had used all the .net methods used in the C# code within the powershell script and i still get  the below. and the sample C# code doesnt work either 

success      : False
errorCode    : 5
errorMessage :  error occured while trying to get balance.

sent an email to the support team. lets see what they come back with

**Comment by ghost** [comment]
sweet, would love to know what they say about it if they get back to you.
