### ISSUE TITLE
Placing order "at market"

### ISSUE THREAD

**Issue by FtotheD** [BTCMarkets/API#83]
Hi there, I am encountering issues when trying to purchase "at market" because by the time I query the price and then attempt to settle, that particular parcel may already be gone. As a result I receive an error each time.

Is there a way to have the API execute a trade at the best available price (whatever it may be)?

Thank you, 

Fd

**Comment by DaveJMir** [comment]
Can you put "Market" where you're currently putting "Limit" when posting to /order/create?

**Comment by martin-nginio** [comment]
thanks @FtotheD  and @cheriff 

Cloisng the issue. 

Regards,
Martin
