### ISSUE TITLE
Please add XRP and BCH to the API 

### ISSUE THREAD

**Issue by dawatz** [BTCMarkets/API#85]
Hi there, 

XRP and BCH don't seem to be showing up in the API data.
Perhaps because they have only be added recently they haven't yet been addd to the API?

It would be great if they could be added in.
If they have and I've somehow missed it happy to be advised.

Many thanks,
Daryl

**Comment by ghost** [comment]
Not exactly sure what you mean, but I've got a system that trades using these currencies

**Comment by dawatz** [comment]
thanks, this has been resolved and was a mistake at my end.
all good.
