### ISSUE TITLE
API withdrawal fee

### ISSUE THREAD

**Issue by ghost** [BTCMarkets/API#86]
Is there any call that will retrieve the currency specific withdrawal fee?
ie Bitcoins 0.0005 fee when withdrawing to an external bitcoin address

**Comment by meeeee12** [comment]
When withdrawing your block-chain assets to a digital wallet there is a flat fee of 0.22%.

As described here:
https://www.btcmarkets.net/fees

**Comment by meeeee12** [comment]
Use this route: "/account/{instrument}/{currency}/tradingfee"

**Comment by ghost** [comment]
Hey, cheers for the reply.
I don’t think I can use this to get the transaction fee for withdrawing a currency. Doesn’t this only give you the fee for trading between currencies?

**Comment by meeeee12** [comment]
Sorry, I make a mistake. You are right.

**Comment by justin-ngin** [comment]
Hi @jdceds,

You just want to be able to receive the withdrawal fees listed on the fees page of BTCMarkets.net available through an endpoint on the API correct? Or is there additional information you want from such an endpoint? I'll add it to the development backlog.

Regards,
Justin

**Comment by ghost** [comment]
hey @justin-ngin,

yup, that would be perfect.
Could you post here when that has been released?
Thanks!

**Comment by justin-ngin** [comment]
@jdceds ,

Shouldn't be a problem. Adding it to the development backlog now, and I'll update this issue as well as the wiki when it's about to be released. Thanks for being a part of the BTC Markets community.

Cheers
Justin

**Comment by KonstantinKustau** [comment]
Hello @justin-ngin,

I'm also looking forward to this functional. Do you have any progress in this? I would like to see more data in this request. Such as "enableWithdraw" and "enableDeposit". That is, does the conclusion work for current currency? And does the deposit work for current currency? It will be very convenient. For example this is done at Kucoin: https://api.kucoin.com/v1/market/open/coins 

Thank you very much of your work. Binance is very good exchange.

**Comment by nzaubanker** [comment]
Also waiting for this :).

**Comment by martin-nginio** [comment]
Hi @jdceds 

Thanks for your feedback.

Closing this issue as our latest API now supports the feature reqeusted:
https://api.btcmarkets.net/v3/withdrawal-fees 

Thanks.

Regards,
Martin
