### ISSUE TITLE
24 hour %PriceChange, High Price, Low Price

### ISSUE THREAD

**Issue by bikuz** [BTCMarkets/API#87]
Hi,

Can you please include  24 hour %PriceChange, HighPrice, LowPrice in the tick api 'https://api.btcmarkets.net/market/XRP/AUD/tick' 
so that the response would be
{"bestBid":2.26,
"bestAsk":2.27,
"lastPrice":2.26,
"currency":"AUD",
"instrument":"XRP",
"timestamp":1514548188,
"volume24h":2.3072176E7,
"percentChange24h":  ___________ ,
"high24h":  ___________ ,
"low24h":  ___________ ,
}

**Comment by stephenyao** [comment]
There doesn't seem to be a way to do this. Inspecting the js source from btcmarkets.net, they seem to have a function which loops through all the day from the previous day and find the trade that happened 24 hours ago, and compares it with the last sale price to get the price change...

**Comment by justin-ngin** [comment]
Hi @bikuz ,
This is similar to issue #71 which I closed yesterday. This has been added to our development backlog. I will update the wiki with regards to this change when we get close to deployment.

Thanks,
Justin

**Comment by martin-nginio** [comment]
closing the issue 
the latest API has the statistics mentioned:
https://api.btcmarkets.net/v3/markets/BTC-AUD/ticker

Thanks.
