### ISSUE TITLE
Checking all open orders requires 11 API calls

### ISSUE THREAD

**Issue by natelouisdev** [BTCMarkets/API#88]
I might be missing something here, but is it possible to access all open orders through one API call? Checking each pair requires 11 different API calls which causes throttling issues.

**Comment by meeeee12** [comment]
I use the route " /account/balance" for this.

**Comment by justin-ngin** [comment]
Hi @natelouisdev ,

At the moment, there is not a way to access or obtain all open orders for all trading pairs through the API. However the response provided by @meeeee12 should provide you with an amount of funds tied up in open orders. If there is additional information you'd like to be able to obtain regarding all open orders for all trading pairs, please let me know here and I'll take it up with the engineering team to see what we can do.

Thanks,
Justin

**Comment by scoshil** [comment]
@justin-ngin if we have buy orders on multiple pairs it would not be possible to figure out which pair they are on without separately calling each.

Speaking of which, are the limits stated [here](https://github.com/BTCMarkets/API/wiki/faq) applied per endpoint, or are they accumlated across all endpoints? (E.g. all the endpoints under the 25/10 sec limit share the 1 limit, while all the endpoints under the 10/10 category share another limit?)

**Comment by justin-ngin** [comment]
Hi @scoshil ,

An endpoint to return all open orders, regardless of trading pairs is in the development backlog. 

As far as I know, the limits on the faq page are applied per endpoint listed, and not per group. Please let me know if you're experiencing behavior that suggests otherwise.

Cheers,
Justin

**Comment by justin-ngin** [comment]
Hi @natelouisdev, @meeeee12, @scoshil,

I know it's been a long time coming, but it's finally here. Check out the recently released endpoint for all [Open Orders](https://github.com/BTCMarkets/API/wiki/Trading-API#open-orders-1)

Cheers,
Justin
