### ISSUE TITLE
Increasing API Limits

### ISSUE THREAD

**Issue by ghost** [BTCMarkets/API#90]
I'm creating a sytem that requires more than the (6-10) per 10s account calls available to me, how am I able to get this limit increased? I've tried contacting support a few times and on twitter too.

**Comment by martin-nginio** [comment]
Thanks for your feedback. 

Our latest API release offers higher capacity and better rate limits:
https://api.btcmarkets.net/doc/v3#section/General-notes

If you have any questions or if you need higher capacity please feel free to engage with our support team. 

I'm closing this issue. 

Thanks.

Regards,
Martin
