### ISSUE TITLE
Constant "Authentication failed" error using Google App Script

### ISSUE THREAD

**Issue by soundfx42** [BTCMarkets/API#94]
I've tried everything I can think of, every combination I can think of and all I constantly get is "Authentication failed".

Here is the code I'm using to generate my authentication string (key has been changed)
```
var SystemTimeMilli = Date.now();  
var accountBalInputString = ('/account/balance'+'\n'+SystemTimeMilli+'\n');
var PrivateKey = 'bEDtDJnW0y/Ll4YZitxb+D5sTNnEpQKH67EJRCmQCqN9cvGiB8+IHzB7HjsOs3mSlxLmu4aiPDRpe9anuWzylw==';
PrivateKey = Utilities.base64Decode(PrivateKey, Utilities.Charset.UTF_8);
var BTCsignature = Utilities.base64Encode(Utilities.computeHmacSignature(Utilities.MacAlgorithm.HMAC_SHA_512, accountBalInputString, PrivateKey, Utilities.Charset.UTF_8));
```

When I put it all together this is the `GET` string that is being generated

` {headers={Accept-Charset=UTF-8, Accept=application/json, apikey=8f30aaaa-1977-4a99-9659-11111ad771aa, signature="1cZzfhhF9Ik+QX5+nQi1RicbFMk1RrjLrCspwb26APFkjfMOaqFIOeoYgZgT42CPhDdvC7XWXnPm/ueX38gUJg==", timestamp=1515058794242}, method=get, payload=, followRedirects=true, validateHttpsCertificates=true, useIntranet=false, contentType=application/json, url=https://api.btcmarkets.net/account/balance}`

This results in the following being returned from the API

`{"success":false,"errorCode":1,"errorMessage":"Authentication failed."}`

I've checked and cross checked as best I know how to but have absolutely hit a dead end.

**Comment by meeeee12** [comment]
separate the items in your header using "\r\n" not ","

**Comment by justin-ngin** [comment]
Hello @soundfx42 ,

Using the timestamp you provided and the fake private key in your code snippet, the hmac signature should be this: 

WImZPMYXJ3f7OmlGtmgIWOwmkZ006fMsEOgMmmJalLoXPZX5fbIyKnX0OYzSnsGeFxGQwvMmgFI6fQHnmR2zoA==

Can you please try again with your "private key" above and the timestamp above and compare these signatures?

Thanks,
Justin

**Comment by ukdilmah** [comment]
did you ever resolve this? I have the same problem. I can get HMAC SHA512 working on other exchanges.  I can't replicate the sample HMAC Justin has provided. 

Justin could you please provide an example signing a message without the '\n' characters as these make it tougher to debug / cross-check with online web sites that generate HMACs ? 

Thanks

**Comment by justin-ngin** [comment]
@ukdilmah ,

Using the timestamp: `1515058794242`
the private key: `bEDtDJnW0y/Ll4YZitxb+D5sTNnEpQKH67EJRCmQCqN9cvGiB8+IHzB7HjsOs3mSlxLmu4aiPDRpe9anuWzylw==`
and this string body: `/account/balance1515058794242`  (no newline characters, as requested)

you should be producing the below signature:
`NjqZ8Mgdkj6hrtY/xdKBy1S0kLjU2tA7G+pR2TdOBF45b7+evfpzGH/C/PiNHEDvuiRChRBlRo3AGJ7Gcvlwqw==`

I generated this signature from a node.js client. I will try to find out if google script processes newline characters differently than node, and might be causing an invalid hmac to be created.

Please let me know if you can replicate this signature.

Cheers,
Justin

**Comment by pgulline** [comment]
@justin-ngin ,
For the example provided, should the following bash work?
echo -n '/account/balance1515058794242' | openssl dgst -sha512 -hmac bEDtDJnW0y/Ll4YZitxb+D5sTNnEpQKH67EJRCmQCqN9cvGiB8+IHzB7HjsOs3mSlxLmu4aiPDRpe9anuWzylw== | base64

**Comment by queenvictoria** [comment]
Ok step by step. Thanks to everyone who wrote up their part of the fix.

1. Open your script editor (I'm in Sheets so `Tools > Script editor`).
1. Create a new script to hold the `jsSHA` library (see https://github.com/BTCMarkets/API/issues/75#issuecomment-355494151). Call it `jsSHA.gs` or `jsSHA512.js`. This is to replace Google's implementation of SHA as it [doesn't support binary secrets](https://issuetracker.google.com/issues/36757327).
1. Paste in the code from the [raw script](https://raw.githubusercontent.com/Caligatio/jsSHA/v2.3.1/src/sha512.js).
1. Return to your `Code.gs` script. _Note: You don't need to require `sha512` nor add it as a resource library_.
1. Where you are calling the BTCMarkets API use the following pattern.

```javascript
  // Define your key and secret
  var APIKEY = "xxxx";
  var APISECRET = "xxxx";

  var NONCE = Date.now();
  var PATH = '/account/balance'
  var URI = "https://api.btcmarkets.net" + PATH;
 // Note I have no query parameters so the message is very plain.
  var MESSAGE = PATH + "\n" + NONCE + "\n";

  var shaObj = new jsSHA("SHA-512", "TEXT"); // The script we copied.
  shaObj.setHMACKey(APISECRET, "B64");
  shaObj.update(MESSAGE);
  var SIGNATURE = shaObj.getHMAC("B64");

  var headers = {
    'Accept' : 'application/json',
    'Accept-Charset' : 'UTF-8',
    'Content-Type' : 'application/json',
    'Cache-Control': 'no-cache',
    'apikey' : APIKEY,
    'timestamp' : NONCE + "", // Turn timestamp into a string
    'signature' : SIGNATURE
  };
  
  var params = {
    headers: headers,
  };

  var call = UrlFetchApp.fetch('https://api.btcmarkets.net/account/balance', params);
  var obj = JSON.parse(call.getContentText());
  // Do something with obj
  Logger.log(obj);
```

**Comment by martin-nginio** [comment]
Closing this issue. 

Thanks everyone for help with troubleshooting.
