### ISSUE TITLE
How to get deposit addresses 

### ISSUE THREAD

**Issue by sigulete** [BTCMarkets/API#96]
Is there a way to get deposit addresses for crypto wallets using the API?
I need to obtain the addresses to make deposits to: BTC, XRP, etc..

**Comment by justin-ngin** [comment]
Hi @sigulete ,

I'm adding this to the development backlog. Please feel to update this issue with any additional ideas you may have regarding this feature.

Thanks,
Justin

**Comment by dysfunct** [comment]
@justin-ngin Just wanted to check in and see what the timeline might look like for this feature. Working to integrate with BTCM but this would be a necessary feature to do so. Thanks!

**Comment by justin-ngin** [comment]
Hi @dysfunct ,

It is still on the backlog, but I will see if I can increase it's priority for the team to get it out sooner. Thanks for your patience.

Cheers!
Justin

**Comment by taghvaei** [comment]
any update on this ? I think deposit update is one of vital elements in any exchange API doc.

**Comment by justin-ngin** [comment]
Hi @taghvaei ,

We haven't forgotten about this API feature request. At the moment, we are working on the platform, but this is quite high priority when we return to API development. I'll be happy to share when we are closer to a release of this feature.

Thanks,
Justin

**Comment by shazbert** [comment]
Hi @justin-ngin, 
Sorry to nag, any updates on this?

**Comment by justin-ngin** [comment]
Hi @shazbert ,

We're hoping to start development on this soon. I know this is a feature that many users are asking for, and I want to get it out there for you.

Regards,
Justin

**Comment by JoshuaBatty** [comment]
Just leaving my support for this feature landing soon. it's pretty essential for this to be in the API soon.

**Comment by martin-nginio** [comment]
Hi @sigulete, @dysfunct, @taghvaei, @JoshuaBatty 

Thank you all for your feedback. 

We have recently released a new API version (v3) with ability to get a new deposit addresses:
https://api.btcmarkets.net/doc/v3#tag/Fund-Management-APIs/paths/~1v3~1addresses/get

The same feature is also available for the existing API (v2) as per below:
https://github.com/BTCMarkets/API/wiki/Fund-Transfer-API#get-deposit-address---updated-052219

Thank you again.

Regards,
Martin

**Comment by martin-nginio** [comment]
closing the issue 

Thanks @sigulete  and @taghvaei  for your feedback. 

Regards,
Martin
