### ISSUE TITLE
Authentication failed. invalid timestamp

### ISSUE THREAD

**Issue by tigerhalsey** [BTCMarkets/API#99]
Hello,
I am having an issue with trying to get my trading fee data or doing any API call where i need to authenticate. Last week my application was working fine however this week I am getting the following error back from the API every time I try and make a call:
{"success":false,"errorCode":1,"errorMessage":"Authentication failed. invalid timestamp"}

I'm developing the code in C#, I am also getting the same error in your sample code example for C#.
How do I fix the issue of having an invalid timestamp?

Here is the code I am getting to find the timestamp:
```
            //get the epoch timestamp to be used as the nonce
            var unixTime = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            timestamp = ((long) (DateTime.Now - unixTime).TotalMilliseconds).ToString();
```

Any help would be much appriacted

Cheers
Tim

**Comment by justin-ngin** [comment]
Hi @tigerhalsey,

[https://github.com/jyoung80/csharp_BTC_Markets_Harness/blob/origin/BTC_Markets_Harness/Helpers/ConversionHelper.cs](https://github.com/jyoung80/csharp_BTC_Markets_Harness/blob/origin/BTC_Markets_Harness/Helpers/ConversionHelper.cs
)

In the example you mentioned above, the sample code uses

`var unixTime = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);`
`var secondsSinceEpoch = (long) (DateTime.**UtcNow** - unixTime).TotalMilliseconds;`

whereas the snippet you provided only uses DateTime.Now.

Have you tried matching the sample already?

Regards,
Justin

**Comment by tigerhalsey** [comment]
Hello Justin,
Thank you for your reply.
I was trying both the following:
`            //get the epoch timestamp to be used as the nonce
            var unixTime = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            timestamp = ((long) (DateTime.UtcNow - unixTime).TotalMilliseconds).ToString();
`
And
`            //get the epoch timestamp to be used as the nonce
            var unixTime = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            timestamp = ((long) (DateTime.Now - unixTime).TotalMilliseconds).ToString();
`
To see if i get the same result, both return the same message.
I have pulled the sample code down from GitHub and ran that as well and am getting the same message.

I'm using windows 10 building the code in C#
As of writing this the current time stamp i generated was 1515630685093

Do you need more information?

Cheers
Tim

**Comment by tigerhalsey** [comment]
Also my same code was working fine early last fortnight when I first developed my code if that makes any difference.

Cheers
Tim

**Comment by justin-ngin** [comment]
Hi Tim,

After speaking with the dev team, you would be receiving that message in the response if the timestamp included has too high of a variance from the API server. If both your code and the sample c# code are producing the same authentication error, I'd suggest verifying that your machine is synced with an NTP server. Please let me know if that resolves the issue.

Regards,
Justin

**Comment by tigerhalsey** [comment]
Can you please point me in the right direction on how I sync my computer with an NTP server.
As far as i am aware my computer gets the datetime from the internet already.

Any help would be great as I am not too experienced in NTP.

Cheers
Tim

**Comment by justin-ngin** [comment]
Hi Tim,

Here are some resources for verifying the the time on your local machine:
[https://www.epochconverter.com/](https://www.epochconverter.com/)
[https://time.is/](https://time.is/)

Below are also some resources for checking which time server you're currently syncing with, forcing a sync, or changing servers.
[https://www.windowscentral.com/how-manage-time-servers-windows-10](https://www.windowscentral.com/how-manage-time-servers-windows-10)
[https://superuser.com/questions/954477/where-do-i-find-the-internet-time-ntp-settings-in-windows-10](https://superuser.com/questions/954477/where-do-i-find-the-internet-time-ntp-settings-in-windows-10)
[https://winaero.com/blog/configure-internet-time-ntp-options-in-windows-10/](https://winaero.com/blog/configure-internet-time-ntp-options-in-windows-10/)

Regards,
Justin

**Comment by tigerhalsey** [comment]
Thank you for your help.
My code is now working today.
I update getting the time to be:
`
            timestamp =
                ((long) (DateTime.UtcNow - new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalMilliseconds)
                    .ToString();
`

Now i am receiving the data.
